// src/views/Feat-0708.vue
<template>
  <div>
    <van-popup
      v-model="popupVisible"
      position="bottom"
      :style="{ height: '40%' }"
    >
      <van-area
        columns-num="2"
        confirm-button-text="完成"
        :area-list="areaList"
        @confirm="confirm"
      />
    </van-popup>
  </div>
</template>
<script>
import { areaList } from '@vant/area-data';
export default {
  data() {
    return {
      areaList: Object.freeze(areaList),
      popupVisible: true,
    };
  },
  methods: {
    confirm(e) {
      this.popupVisible = false;
      console.log(e);
    },
  },
};
</script>

// src/views/Feat-0708.jsx
import { areaList } from '@vant/area-data';
import styled from 'styled-components-vue';
const Wrapper = styled.div`
  .van-picker__confirm {
    color: red;
  }
`;
export default {
  render() {
    return (
      <Wrapper>
        <van-popup
          v-model={this.popupVisible}
          position="bottom"
          style={{ height: '40%' }}
        >
          <van-area
            columns-num="2"
            confirm-button-text="完成"
            area-list={areaList}
            onConfirm={this.confirm}
          />
        </van-popup>
      </Wrapper>
    );
  },
  data() {
    return {
      popupVisible: true,
    };
  },
  methods: {
    confirm(e) {
      this.popupVisible = false;
      console.log(e);
    },
  },
};
